service: serverless-aws-python

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-central-1

plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

package:
  exclude:
    - node_modules/**
    - venv/**

functions:
  ping:
    handler: ping.main
    events:
      - http:
          path: /ping
          method: get
          cors: true